### ISSUE TITLE
Feature Suggestion: 6 sockets regex

### ISSUE THREAD

**Issue by Ateya9** [veiset/poe-vendor-string#22]
I've been using a regex for 6 sockets for a while now;

([rgbw].){5}[rgbw]

It might be worth adding to the vendor search page? Though it's worth noting that this does highlight 6 links as well.

**Comment by Aradiv** [comment]
`(?=.+ )([rgbw].){5}[rgbw]`
this will find only six sockets no six links

**Comment by veiset** [comment]
Solved by @Aneduna in #29!

**Comment by Aneduna** [comment]
Uhm actually this is asking for 6 sockets not 6 links. I don't think this is solved by my commit :)

**Comment by veiset** [comment]
Oh my bad. Reopening it. I'll solve this later.

**Comment by veiset** [comment]
And by later I mean I just fixed with 396ed96, it should be live now. Sorry about that! 😁
